### PR TITLE
Fix loading of JSON catalogs in Puppet 4.x

### LINKED ISSUE #15: diff fails with 4.2.1
(with puppet enterprise 2015.2)

```
4.2.1 root@training:/etc/puppetlabs/code/environments/production/modules/catalog_diff # puppet catalog diff --trace catalog1.pson catalog2.pson 
Error: Add --debug for realtime output, add --render-as {json,yaml} for parsed output
Error: undefined method `version' for #<Hash:0x00000002dc76c8>
/etc/puppetlabs/code/environments/production/modules/catalog_diff/lib/puppet/catalog-diff/differ.rb:49:in `block in diff'
/etc/puppetlabs/code/environments/production/modules/catalog_diff/lib/puppet/catalog-diff/differ.rb:30:in `each'
/etc/puppetlabs/code/environments/production/modules/catalog_diff/lib/puppet/catalog-diff/differ.rb:30:in `diff'
/etc/puppetlabs/code/environments/production/modules/catalog_diff/lib/puppet/face/catalog/diff.rb:122:in `block (3 levels) in <top (required)>'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/interface/action.rb+eval[wrapper]:242:in `diff'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/face_base.rb:248:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:352:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:446:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:128:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Error: Try 'puppet help catalog diff' for usage
```

once i replace catalog.version with something meaningless it's not getting better:

```
4.2.1 root@training:/etc/puppetlabs/code/environments/production/modules/catalog_diff # puppet catalog diff --trace catalog1.pson catalog2.pson 
Error: Add --debug for realtime output, add --render-as {json,yaml} for parsed output

--------------------------------------------------------------------------------
catalog2                                                                    NaN% 
--------------------------------------------------------------------------------
Old version:    whatever
New version:    whatever
Total resources in old: 0
Total resources in new: 0
Catalag percentage added:       NaN
Catalog percentage removed:     0.00
Catalog percentage changed:     0.00
Added and removed resources:    0 / 0
Node percentage:        NaN
Node differences:       0






--------------------------------------------------------------------------------
1 out of 1 nodes changed.                                                   NaN% 
--------------------------------------------------------------------------------

Nodes with the most changes by percent changed:
1. catalog2                                                                 NaN%

Nodes with the most changes by differeces:
1. catalog2                                                                   0false
```

it seems whole new catalog conversion is needed for puppet 4.2.1.

(test files are those from ripienaar module)

### PR DESCRIPTION
**Pull request by dalen**
Fixes #15

### CODE REVIEW

**Comment by kylog** [comment]
:+1:

**Comment by raphink** [comment]
I'm guessing this does the same as https://github.com/raphink/puppet-catalog-diff/commit/56f2ee44dfffd357cd8ca8aa64da35329b9f454d ?

**Comment by dalen** [comment]
@raphink a bit different way of doing it. But I guess the end result is the same.

**Comment by raphink** [comment]
OK. So long as it works, that's what matters.

**Pull request merged**
