### PR TITLE
Improve PuppetDB support

### PR DESCRIPTION
**Pull request by raphink**
Improve/fix PuppetDB support and expose it in the diff action.

### CODE REVIEW

**Comment by acidprime** [comment]
Needs a rebase

**Comment by raphink** [comment]
Rebased.

**Comment by acidprime** [comment]
Looks like you need to again based on the other merge

**Comment by acidprime** [comment]
@raphink ^^

**Comment by acidprime** [comment]
I will cut a v1.5 release as soon as this is complete

**Comment by acidprime** [comment]
grabbed it myself here
https://github.com/acidprime/puppet-catalog-diff/commit/c567a48fe75715a1d30e1d02dcc49c339b470cb8

**Pull request closed without merging**
